-- Tape-measure circumference fields on measurements
ALTER TABLE "measurements" ADD COLUMN IF NOT EXISTS "neckCm" DOUBLE PRECISION;
ALTER TABLE "measurements" ADD COLUMN IF NOT EXISTS "shoulderCm" DOUBLE PRECISION;
ALTER TABLE "measurements" ADD COLUMN IF NOT EXISTS "bicepsLeftCm" DOUBLE PRECISION;
ALTER TABLE "measurements" ADD COLUMN IF NOT EXISTS "bicepsRightCm" DOUBLE PRECISION;
ALTER TABLE "measurements" ADD COLUMN IF NOT EXISTS "chestCm" DOUBLE PRECISION;
ALTER TABLE "measurements" ADD COLUMN IF NOT EXISTS "waistCm" DOUBLE PRECISION;
ALTER TABLE "measurements" ADD COLUMN IF NOT EXISTS "abdomenCm" DOUBLE PRECISION;
ALTER TABLE "measurements" ADD COLUMN IF NOT EXISTS "hipCm" DOUBLE PRECISION;
ALTER TABLE "measurements" ADD COLUMN IF NOT EXISTS "thighLeftCm" DOUBLE PRECISION;
ALTER TABLE "measurements" ADD COLUMN IF NOT EXISTS "thighRightCm" DOUBLE PRECISION;
ALTER TABLE "measurements" ADD COLUMN IF NOT EXISTS "calfLeftCm" DOUBLE PRECISION;
ALTER TABLE "measurements" ADD COLUMN IF NOT EXISTS "calfRightCm" DOUBLE PRECISION;
