ALTER TABLE "daily_trackers" ADD COLUMN IF NOT EXISTS "proteinGrams" DOUBLE PRECISION;

CREATE TABLE IF NOT EXISTS "nudge_logs" (
    "id" TEXT NOT NULL,
    "clientId" TEXT NOT NULL,
    "category" TEXT NOT NULL,
    "scheduledDate" TIMESTAMP(3) NOT NULL,
    "scheduledTime" TEXT NOT NULL DEFAULT '',
    "sentAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "nudge_logs_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "nudge_logs_clientId_category_scheduledDate_scheduledTime_key" ON "nudge_logs"("clientId", "category", "scheduledDate", "scheduledTime");

DO $$ BEGIN
  ALTER TABLE "nudge_logs" ADD CONSTRAINT "nudge_logs_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "clients"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

ALTER TYPE "EmailTemplate" ADD VALUE IF NOT EXISTS 'NUDGE_HYDRATION';
ALTER TYPE "EmailTemplate" ADD VALUE IF NOT EXISTS 'NUDGE_PROTEIN';
ALTER TYPE "EmailTemplate" ADD VALUE IF NOT EXISTS 'NUDGE_COMPRESSION';
ALTER TYPE "EmailTemplate" ADD VALUE IF NOT EXISTS 'NUDGE_MOVEMENT';
ALTER TYPE "EmailTemplate" ADD VALUE IF NOT EXISTS 'NUDGE_SLEEP';
ALTER TYPE "EmailTemplate" ADD VALUE IF NOT EXISTS 'NUDGE_PEPTIDE_UPCOMING';
ALTER TYPE "EmailTemplate" ADD VALUE IF NOT EXISTS 'NUDGE_PEPTIDE_OVERDUE';
ALTER TYPE "EmailTemplate" ADD VALUE IF NOT EXISTS 'NUDGE_APPOINTMENT';
ALTER TYPE "EmailTemplate" ADD VALUE IF NOT EXISTS 'NUDGE_WEEKLY_CHECKIN';
