ALTER TABLE "clients" ADD COLUMN IF NOT EXISTS "peptideJourneyInviteSentAt" TIMESTAMP(3);
ALTER TABLE "clients" ADD COLUMN IF NOT EXISTS "peptideJourneyInviteSentByName" TEXT;
ALTER TYPE "EmailTemplate" ADD VALUE IF NOT EXISTS 'PEPTIDE_JOURNEY_INVITE';
